# Generated by Django 4.1.13 on 2025-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_info',
            name='student_course_starttime',
            field=models.DateTimeField(null=True),
        ),
    ]
