# Generated by Django 4.1.13 on 2025-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0002_alter_students_info_student_course_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info',
            name='allocate',
            field=models.BooleanField(default=False),
        ),
    ]
