# Generated by Django 4.1.13 on 2025-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0004_alter_questions_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
